 version: '3.3'

 services:
        nginx:
             image: nginx:latest
             ports:
                 - "8000:80"
             volumes:
                 - ./:/etc/nginx/conf.d  

        app1:
                image: containous/whoami
        app2:
                image: containous/whoami
